### ISSUE TITLE
Bonjour, j'ai un petit soucis et j'ai pas utiliser depuis 201x :D

### ISSUE THREAD

**Issue by F-Fichter** [kalliope-project/kalliope_starter_fr#3]
Bonjour,

J'avais a l'epoque installer sur un orange pi zero 512 Mo, et la je le ressort et tente de remettre en fonction.
Sur armbian 👍🏽  bullseye

# PLEASE DO NOT EDIT THIS FILE
BOARD=orangepizero
BOARD_NAME="Orange Pi Zero"
BOARDFAMILY=sun8i
BUILD_REPOSITORY_URL=https://github.com/armbian/build
BUILD_REPOSITORY_COMMIT=1a8daf0
VERSION=23.02.2
LINUXFAMILY=sunxi
ARCH=arm
IMAGE_TYPE=stable
BOARD_TYPE=conf
INITRD_ARCH=arm
KERNEL_IMAGE_TYPE=stable
IMAGE_UUID=af901c27-a04d-4b84-af70-47d131f0b185

Pouvez vous m'aidez sur ce point, svp

fran@orangepizero:~/kalliope_starter_fr$ kalliope start
Starting REST API Listening port: 5000
Starting Kalliope
Press Ctrl+C for stopping
Starting order signal
Exception in thread <class 'kalliope.signals.order.order.Order'>:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/kalliope/trigger/snowboy/snowboydecoder.py", line 119, in open_audio
    self.stream_in = self.audio.open(
  File "/usr/local/lib/python3.9/dist-packages/pyaudio/__init__.py", line 639, in open
    stream = PyAudio.Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pyaudio/__init__.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9997] Invalid sample rate

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/kalliope/trigger/snowboy/snowboydecoder.py", line 119, in open_audio
    self.stream_in = self.audio.open(
  File "/usr/local/lib/python3.9/dist-packages/pyaudio/__init__.py", line 639, in open
    stream = PyAudio.Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pyaudio/__init__.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9997] Invalid sample rate

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/kalliope/trigger/snowboy/snowboydecoder.py", line 119, in open_audio
    self.stream_in = self.audio.open(
  File "/usr/local/lib/python3.9/dist-packages/pyaudio/__init__.py", line 639, in open
    stream = PyAudio.Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pyaudio/__init__.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9997] Invalid sample rate

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/kalliope/trigger/snowboy/snowboydecoder.py", line 119, in open_audio
    self.stream_in = self.audio.open(
  File "/usr/local/lib/python3.9/dist-packages/pyaudio/__init__.py", line 639, in open
    stream = PyAudio.Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pyaudio/__init__.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9997] Invalid sample rate

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/kalliope/trigger/snowboy/snowboydecoder.py", line 119, in open_audio
    self.stream_in = self.audio.open(
  File "/usr/local/lib/python3.9/dist-packages/pyaudio/__init__.py", line 639, in open
    stream = PyAudio.Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pyaudio/__init__.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9997] Invalid sample rate

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/kalliope/trigger/snowboy/snowboydecoder.py", line 119, in open_audio
    self.stream_in = self.audio.open(
  File "/usr/local/lib/python3.9/dist-packages/pyaudio/__init__.py", line 639, in open
    stream = PyAudio.Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pyaudio/__init__.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9997] Invalid sample rate

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/dist-packages/kalliope/signals/order/order.py", line 89, in run
    self.start_trigger()
  File "/usr/local/lib/python3.9/dist-packages/transitions/core.py", line 402, in trigger
    return self.machine._process(func)
  File "/usr/local/lib/python3.9/dist-packages/transitions/core.py", line 1223, in _process
    self._transition_queue[0]()
  File "/usr/local/lib/python3.9/dist-packages/transitions/core.py", line 416, in _trigger
    self._process(event_data)
  File "/usr/local/lib/python3.9/dist-packages/transitions/core.py", line 439, in _process
    if trans.execute(event_data):
  File "/usr/local/lib/python3.9/dist-packages/transitions/core.py", line 277, in execute
    self._change_state(event_data)
  File "/usr/local/lib/python3.9/dist-packages/transitions/core.py", line 287, in _change_state
    event_data.machine.get_state(self.dest).enter(event_data)
  File "/usr/local/lib/python3.9/dist-packages/transitions/core.py", line 129, in enter
    event_data.machine.callbacks(self.on_enter, event_data)
  File "/usr/local/lib/python3.9/dist-packages/transitions/core.py", line 1146, in callbacks
    self.callback(func, event_data)
  File "/usr/local/lib/python3.9/dist-packages/transitions/core.py", line 1167, in callback
    func(*event_data.args, **event_data.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/kalliope/signals/order/order.py", line 96, in start_trigger_process
    self.trigger_instance = TriggerLauncher.get_trigger(settings=self.settings, callback=self.trigger_callback)
  File "/usr/local/lib/python3.9/dist-packages/kalliope/core/TriggerLauncher.py", line 32, in get_trigger
    trigger_instance = Utils.get_dynamic_class_instantiation(package_name="trigger",
  File "/usr/local/lib/python3.9/dist-packages/kalliope/core/Utils/Utils.py", line 150, in get_dynamic_class_instantiation
    return klass(**parameters)
  File "/usr/local/lib/python3.9/dist-packages/kalliope/trigger/snowboy/snowboy.py", line 63, in __init__
    self.detector = snowboydecoder.HotwordDetector(keyword_files,
  File "/usr/local/lib/python3.9/dist-packages/kalliope/trigger/snowboy/snowboydecoder.py", line 115, in __init__
    self.open_audio(audio_callback)
  File "/usr/local/lib/python3.9/dist-packages/kalliope/trigger/snowboy/snowboydecoder.py", line 138, in open_audio
    self.open_audio(audio_callback, i)
  File "/usr/local/lib/python3.9/dist-packages/kalliope/trigger/snowboy/snowboydecoder.py", line 138, in open_audio
    self.open_audio(audio_callback, i)
  File "/usr/local/lib/python3.9/dist-packages/kalliope/trigger/snowboy/snowboydecoder.py", line 138, in open_audio
    self.open_audio(audio_callback, i)
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.9/dist-packages/kalliope/trigger/snowboy/snowboydecoder.py", line 132, in open_audio
    raise SnowboyOpenAudioException(
kalliope.trigger.snowboy.snowboydecoder.SnowboyOpenAudioException: ('Error while trying to open audio: %', "OSError(-9997, 'Invalid sample rate')")

Merci

**Comment by Sispheor** [comment]
Hi, answering in English as it may help other users.
Type the error you got in the main core project issue page and you'll find the workaround.

**Comment by F-Fichter** [comment]
Hello ok,

apt get install pulseaudio and /etc/asound.conf or ~.asoundrc  file

Now it run !

Good, because all other are very not good in small machine like orange pi zero 512M, only kalliope work fine and no wait.

Thk
:)

**Comment by F-Fichter** [comment]
At this time for make .pmdl, is hard to find, for change this i use a docker container very cool !

docker pull  rhasspy/snowboy-seasalt  ( i use a kvm debian docker )
docker run -it -p 8000:8000 rhasspy/snowboy-seasalt

and go http 8000 for create you re hown .pmdl
